[default]
PROJECT_NAME = "zenndi-auth"
VERSION = "0.1.0"

# JWT Settings
JWT_PRIVATE_KEY_PATH = "keys/private.pem"
JWT_PUBLIC_KEY_PATH = "keys/public.pem"
JWT_ACCESS_TOKEN_EXPIRE_MINUTES = 30
JWT_REFRESH_TOKEN_EXPIRE_DAYS = 30
JWT_ALGORITHM = "RS256"

# Security
PASSWORD_MIN_LENGTH = 8
BCRYPT_ROUNDS = 12
MAX_LOGIN_ATTEMPTS = 5
LOCKOUT_DURATION_MINUTES = 15

# 2FA
TOTP_ISSUER_NAME = "Zenny"
TOTP_INTERVAL = 30

# Rate Limiting
RATE_LIMIT_LOGIN = "5/minute"
RATE_LIMIT_REGISTER = "3/minute"

# email
FRONTEND_URL = "http://localhost:8000/api/v1/auth"
MAIL_FROM = "contato@nandidigitalworks.com.br"
MAIL_FROM_NAME = "Nandi Digital Works"
RATE_LIMIT_CAPACITY = 300
RATE_LIMIT_REFILL_PER_SEC = 5.0 # 300/60
ALLOWED_ORIGINS = [
    "http://localhost:5173",
    "http://localhost:3000",
    "http://localhost:8000",
    "http://127.0.0.1:5173",
    "http://127.0.0.1:3000",
    "http://127.0.0.1:8000",
    "https://app.zenndi.com.br",
    "http://host.docker.internal:8000",
    "http://host.docker.internal:5173",
    "http://host.docker.internal:3000",
]
ALLOW_ORIGINS_DEV = "True"

# Redis
REDIS_URL = "redis://redis:6379/0"


[prod]
ENV_MODE = "prod"
POSTGRES_HOST = "db"
DATABASE_URL = "postgresql+asyncpg://{POSTGRES_USER}:{POSTGRES_PASSWORD}@{POSTGRES_HOST}:5432/{POSTGRES_DB}"

